### ISSUE TITLE
Suggestion: this client is very good

### ISSUE THREAD

**Issue by dominikaaaa** [cristiioan/LionClient#1]
I'm saying that this project is going to be the best client.

**Comment by cristiioan** [comment]
@dominikaaaa thanks.

**Comment by dominikaaaa** [comment]
You're literally 11 years old, you're not old enough to have GitHub or discord legally.

**Comment by Ilidumb** [comment]
![image](https://user-images.githubusercontent.com/42698710/87787635-42a62880-c83c-11ea-9815-97d82a80e7d2.png)
pogu reported for underage pogu

**Comment by EmeraldSnorlax** [comment]
POG

**Comment by ricoip** [comment]
we be putting the pog in the champ

**Comment by StijnSimons** [comment]
This is actually pog

**Comment by StijnSimons** [comment]
- [X] Salhack
- [X] Underage
- [X] Unironic

what more do you want

**Comment by ScanmanTM** [comment]
📸

**Comment by StijnSimons** [comment]
As future suggestion, i recommend we change this line to something more fitting, anyone got any ideas?
https://github.com/cristiioan/LionClient/blob/master/src/main/java/me/ionar/salhack/SalHackMod.java#L18

**Comment by ricoip** [comment]
![image](https://user-images.githubusercontent.com/32032824/87788291-b6adf400-c86f-11ea-9b77-6b337291fe7a.png)
The beauty of open source.

**Comment by RealIndrit** [comment]
https://github.com/cristiioan/LionClient/blob/master/src/main/java/me/ionar/salhack/SalHackMod.java#L18 >> SkidPact

**Comment by mr-nv** [comment]
nice client even discord rpc doesnt work
how did you manage to break that????

**Comment by dominikaaaa** [comment]
why does it take 2 weeks to build a salhack skid

![Screenshot_20200717-084406.png](https://user-images.githubusercontent.com/17222512/87789416-04dddb80-c80d-11ea-807e-458b2dbc2bb0.png)

**Comment by EmeraldSnorlax** [comment]
https://web.archive.org/web/20200717130913/https://github.com/cristiioan/LionClient/issues/1
